/* 
Agrega todas as features dos cliente:
- Features Transacionais;
- Features relacionadas ao Ciclo de Vida;
- Features relacionadas à Plataforma de Cursos.

O objetivo é realizar predições com as features em data de referência mais recente 
*/
SELECT t1.dtRef,
       t1.idCliente,
       t1.idadeDias,
       t1.qtdeAtivacaoVida,
       t1.qtdeAtivacaoD7,
       t1.qtdeAtivacaoD14,
       t1.qtdeAtivacaoD28,
       t1.qtdeAtivacaoD56,
       t1.qtdeTransacaoVida,
       t1.qtdeTransacaoD7,
       t1.qtdeTransacaoD14,
       t1.qtdeTransacaoD28, 
       t1.qtdeTransacaoD56,
       t1.saldoVida,
       t1.saldoD7,
       t1.saldoD14,
       t1.saldoD28,
       t1.saldoD56,
       t1.qtdePontosPosVida,
       t1.qtdePontosPosD7,
       t1.qtdePontosPosD14,
       t1.qtdePontosPosD28,
       t1.qtdePontosPosD56, 
       t1.qtdePontosNegVida,
       t1.qtdePontosNegD7,
       t1.qtdePontosNegD14,
       t1.qtdePontosNegD28,
       t1.qtdePontosNegD56,
       t1.qtdeTransacaoManha,
       t1.qtdeTransacaoTarde,
       t1.qtdeTransacaoNoite,
       t1.pctTransacaoManha, 
       t1.pctTransacaoTarde, 
       t1.pctTransacaoNoite, 
       t1.qtdeTransacaoDiaVida, 
       t1.qtdeTransacaoDiaD7, 
       t1.qtdeTransacaoDiaD14, 
       t1.qtdeTransacaoDiaD28, 
       t1.qtdeTransacaoDiaD56, 
       t1.pctAtivacaoMAU, 
       t1.qtdeHorasVida,
       t1.qtdeHorasD7,
       t1.qtdeHorasD14,
       t1.qtdeHorasD28,
       t1.qtdeHorasD56,
       t1.avgIntervaloDiasVida,
       t1.avgIntervaloDiasD28,
       t1.qtdeChatMessage,
       t1.qtdeAirflowLover,
       t1.qtdeRLover,
       t1.qtdeListaPresenca,
       t1.qtdePresencaStreak,
       t1.qtdeTrocaDePontosStreamElements,
       t1.qtdeReembolsoTrocaDePontosStreamElements,
       t1.qtdeRpg,
       t1.qtdeChurnModel,
       t2.qtdeFrequencia,
       t2.descLifeCycleAtual,
       t2.descClusterAtual,
       t2.descLifeCycleD28,
       t2.descClusterD28,
       t2.pctCurioso,
       t2.pctFiel,
       t2.pctTurista,
       t2.pctDesencantado,
       t2.pctZumbi,
       t2.pctReconquistado,
       t2.pctReborn,
       t2.avgFreqGrupo, 
       t2.ratioFreqGrupo,
       t3.qtdeCursosCompletos,
       t3.qtdeCursosIncompletos,
       t3.carreira,
       t3.coletaDados2024,
       t3.dsDatabricks2024,
       t3.dsPontos2024,
       t3.estatistica2024,
       t3.estatistica2025,
       t3.github2024,
       t3.github2025,
       t3.go2026,
       t3.iaCanal2025,
       t3.lagoMago2024,
       t3.loyaltyPredict2025 ,
       t3.machineLearning2025,
       t3.matchmakingTramparDeCasa2024,
       t3.ml2024,
       t3.mlflow2025,
       t3.nekt2025,
       t3.pandas2024,
       t3.pandas2025,
       t3.plataformaMl2026,
       t3.python2024,
       t3.python2025,
       t3.speedF1,
       t3.sql2020,
       t3.sql2025,
       t3.streamlit2025,
       t3.tramparLakehouse2024,
       t3.tseAnalytics2024,
       t3.qtdDiasUltimaAtiv 
FROM fs_transacional AS t1

LEFT JOIN fs_life_cycle AS t2
    -- Features do mesmo cliente e da mesma data de refeRência 
    ON t1.idCliente = t2.idCliente
AND t1.dtRef = t2.dtRef

LEFT JOIN fs_education AS t3
    -- Features do mesmo cliente e da mesma data de refeRência 
    ON t1.idCliente = t3.idCliente
AND t1.dtRef = t3.dtRef

-- Seleciona a data de referência mais recente 
WHERE t1.dtRef = (SELECT MAX(dtRef) FROM fs_transacional)